title: Loki Huang
description: I know nothing

url: http://huyfaeng.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Cat1
   url:  /cat1.html
 - title: Cat2
   url:  /cat2.html
 - title: Contact
   url: /contact
 - title: About
   url: /about

social:
   github: huyfaeng
   twitter: huyfaeng
   facebook: huyfaeng
   email: huyfaeng@gmail.com

google_analytics: "UA-74969833-1"
